//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOPNET_WindowsPresentationFoundation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OOPNET_WindowsPresentationFoundation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string areyousure {
            get {
                return ResourceManager.GetString("areyousure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain:.
        /// </summary>
        public static string captain {
            get {
                return ResourceManager.GetString("captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Championship:.
        /// </summary>
        public static string championship {
            get {
                return ResourceManager.GetString("championship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw:.
        /// </summary>
        public static string draw {
            get {
                return ResourceManager.GetString("draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFA code:.
        /// </summary>
        public static string fifacode {
            get {
                return ResourceManager.GetString("fifacode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal difference:.
        /// </summary>
        public static string goaldiff {
            get {
                return ResourceManager.GetString("goaldiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals conceded:.
        /// </summary>
        public static string goalsconceded {
            get {
                return ResourceManager.GetString("goalsconceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals scored:.
        /// </summary>
        public static string goalsscored {
            get {
                return ResourceManager.GetString("goalsscored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals this game:.
        /// </summary>
        public static string goalsthisgame {
            get {
                return ResourceManager.GetString("goalsthisgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team information.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost:.
        /// </summary>
        public static string loses {
            get {
                return ResourceManager.GetString("loses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main window.
        /// </summary>
        public static string mainwindow {
            get {
                return ResourceManager.GetString("mainwindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games played:.
        /// </summary>
        public static string playedgames {
            get {
                return ResourceManager.GetString("playedgames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player information.
        /// </summary>
        public static string playerinfo {
            get {
                return ResourceManager.GetString("playerinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        public static string res {
            get {
                return ResourceManager.GetString("res", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirt Number:.
        /// </summary>
        public static string shirtnumber {
            get {
                return ResourceManager.GetString("shirtnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team information.
        /// </summary>
        public static string teaminfo {
            get {
                return ResourceManager.GetString("teaminfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins:.
        /// </summary>
        public static string wins {
            get {
                return ResourceManager.GetString("wins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards this game:.
        /// </summary>
        public static string ycardsthisgame {
            get {
                return ResourceManager.GetString("ycardsthisgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
